Exception handlers & Modifiable timeout
CloudburstMC/Network pull request #15
Opened 2020-10-20 10:58 UTC by TobiasG-DE

This PR implements two enhancements for the current Network library:
  - Developers are now able to assign exception handlers as Consumer<Throwable> to RakNetClients and RakNetServers. They are
    called whenever an exception occurs in the pipeline.

  - Developers are able to set the timeout of a RakNetSession, which is SESSION_TIMEOUT_MS by default.

2020-10-23 11:56 UTC, Alemiz112 commented on raknet/src/main/java/com/nukkitx/network/raknet/RakNetClient.java
>              log.error("An exception occurred in RakNet", cause);
What about not logging exception if `exceptionHandlers` is not empty. Handlers could care about logging too.

2020-10-23 13:54 UTC, TobiasG-DE commented on raknet/src/main/java/com/nukkitx/network/raknet/RakNetClient.java
> +    public void clearExceptionHandlers() {
I would, especially makes sense with the latest commit. Maybe you wanna remove the default exception handler before adding own ones. Another way I'm considering is to let the user give the handlers IDs, which they can use to remove specific handlers. I would then map <String, Consumer<Throwable>>

2020-10-23 13:55 UTC, TobiasG-DE commented on raknet/src/main/java/com/nukkitx/network/raknet/RakNetClient.java
>              log.error("An exception occurred in RakNet", cause);
In the latest commit I changed that so logging is the default exception handler, but you can clear it to remove it and add own ones

2020-10-23 16:36 UTC, Alemiz112 commented on raknet/src/main/java/com/nukkitx/network/raknet/RakNetClient.java
> +    public void clearExceptionHandlers() {
Adding way to remove only one exception handler from list would be more useful.

2020-10-26 00:12 UTC, SupremeMortal requested changes

2020-10-26 00:12 UTC, SupremeMortal commented on raknet/src/main/java/com/nukkitx/network/raknet/RakNetClient.java
> +    private final Set<Consumer<Throwable>> exceptionHandlers = Collections.newSetFromMap(new ConcurrentHashMap<>());
Could you use `ConcurrentHashMap.newKeySet()`

2020-10-26 00:12 UTC, SupremeMortal commented on raknet/src/main/java/com/nukkitx/network/raknet/RakNetServer.java
> +    private Set<Consumer<Throwable>> exceptionHandler = Collections.newSetFromMap(new ConcurrentHashMap<>());
Could you use `ConcurrentHashMap.newKeySet()`

2020-10-26 18:43 UTC, TobiasG-DE commented
With the latest commit each handler has an individual Id, which can be used to remove specific handlers. That can be used for example if you want to have different exception handlers in different game stages or else

2020-10-26 19:08 UTC, SupremeMortal approved these changes

2020-10-26 19:09 UTC, merged